batch_size: 16
num_trials: 20
trial_epochs: 8
top_k_params: 5
patience: 45
final_epochs: 150


base_dir_search: runs/sequence_only/search
base_dir_final: runs/sequence_only/final

use_wandb: False
wandb_project: seq_homology_reliability_aware_pfp
wandb_entity:
wandb_mode: offline

search_space:
  learning_rate: [0.0001, 0.0003, 0.001]
  weight_decay: [0.00001, 0.0001, 0.001]
  attn_hidden_dim: [128, 256, 512]
  attn_dropout: [0.0, 0.1, 0.2]
  head_hidden_dim: [512]
  head_dropout: [0.0, 0.1, 0.2]
  lambda_hier: [0.0, 0.001, 0.01]
  pos_weight_cap: [5.0, 10.0, 20.0]



promising_hparams:
  BP:
    learning_rate: 0.001
    weight_decay: 0.001
    attn_hidden_dim: 128
    attn_dropout: 0.1
    head_hidden_dim: 512
    head_dropout: 0.3
    lambda_hier: 0.01
    pos_weight_cap: 5.0

  MF:
    learning_rate: 0.0001
    weight_decay: 0.001
    attn_hidden_dim: 512
    attn_dropout: 0.1
    head_hidden_dim: 512
    head_dropout: 0.2
    lambda_hier: 0.0
    pos_weight_cap: 10.0

  CC:
    learning_rate: 0.001
    weight_decay: 0.001
    attn_hidden_dim: 512
    attn_dropout: 0.2
    head_hidden_dim: 512
    head_dropout: 0.2
    lambda_hier: 0.001
    pos_weight_cap: 20.0